#CLOCKS
# set_property ODT RTT_48 [get_ports "SYSCLK_300_N"]
# set_property PACKAGE_PIN AK16 [get_ports "SYSCLK_300_N"]
# set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports "SYSCLK_300_N"]
# set_property PACKAGE_PIN AK17 [get_ports "SYSCLK_300_P"]
# set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports "SYSCLK_300_P"]
# set_property ODT RTT_48 [get_ports "SYSCLK_300_P"]

# CLK_125MHZ
set_property PACKAGE_PIN G10 [get_ports "sys_clk_p"]
set_property IOSTANDARD  LVDS [get_ports "sys_clk_p"]
set_property PACKAGE_PIN F10 [get_ports "sys_clk_n"]
set_property IOSTANDARD  LVDS [get_ports "sys_clk_n"]

create_clock -add -name sys_clk_pin -period 4.0 -waveform {0 2.0} [get_ports { sys_clk_p }]

# set_property IOSTANDARD LVDS_25 [get_ports "USER_SI570_CLOCK_N"]
# set_property PACKAGE_PIN M26 [get_ports "USER_SI570_CLOCK_N"]
# set_property IOSTANDARD LVDS_25 [get_ports "USER_SI570_CLOCK_P"]
# set_property PACKAGE_PIN M25 [get_ports "USER_SI570_CLOCK_P"]
# set_property PACKAGE_PIN G10 [get_ports "CLK_125MHZ_P"]
# set_property IOSTANDARD  LVDS [get_ports "CLK_125MHZ_P"]
# set_property PACKAGE_PIN F10 [get_ports "CLK_125MHZ_N"]
# set_property IOSTANDARD  LVDS [get_ports "CLK_125MHZ_N"]
# set_property PACKAGE_PIN C23 [get_ports "USER_SMA_CLOCK_N"]
# set_property IOSTANDARD LVDS [get_ports "USER_SMA_CLOCK_N"]
# set_property PACKAGE_PIN D23 [get_ports "USER_SMA_CLOCK_P"]
# set_property IOSTANDARD LVDS [get_ports "USER_SMA_CLOCK_P"]
# set_property PACKAGE_PIN L22 [get_ports "SI5328_INT_ALM_LS"]
# set_property IOSTANDARD LVCMOS18 [get_ports "SI5328_INT_ALM_LS"]
# set_property PACKAGE_PIN K23 [get_ports "SI5328_RST_LS"]
# set_property IOSTANDARD LVCMOS18 [get_ports "SI5328_RST_LS"]
# set_property PACKAGE_PIN AH11 [get_ports "REC_CLOCK_C_N"]
# set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports "REC_CLOCK_C_N"]
# set_property PACKAGE_PIN AG11 [get_ports "REC_CLOCK_C_P"]
# set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports "REC_CLOCK_C_P"]
# set_property PACKAGE_PIN K20 [get_ports "FPGA_EMCCLK"]
# set_property IOSTANDARD LVCMOS18 [get_ports "FPGA_EMCCLK"]
# #SI570_CLOCK/SI5328 CLOCK SELECT
# set_property PACKAGE_PIN F12 [get_ports "SI570_CLK_SEL_LS"]
# set_property IOSTANDARD LVCMOS18 [get_ports "SI570_CLK_SEL_LS"]

# set_property PACKAGE_PIN AN8 [get_ports "CPU_RESET"]
# set_property IOSTANDARD LVCMOS18 [get_ports "CPU_RESET"]

# CPU_RESET
set_property PACKAGE_PIN AN8 [get_ports "ck_rst"]
set_property IOSTANDARD LVCMOS18 [get_ports "ck_rst"]

#GPIO PMOD0
set_property PACKAGE_PIN AK25 [get_ports "ja[0]"]
set_property IOSTANDARD LVCMOS12 [get_ports "ja[0]"]
set_property PACKAGE_PIN AN21 [get_ports "ja[1]"]
set_property IOSTANDARD LVCMOS12 [get_ports "ja[1]"]
set_property PACKAGE_PIN AH18 [get_ports "ja[2]"]
set_property IOSTANDARD LVCMOS12 [get_ports "ja[2]"]
set_property PACKAGE_PIN AM19 [get_ports "ja[3]"]
set_property IOSTANDARD LVCMOS12 [get_ports "ja[3]"]
set_property PACKAGE_PIN AE26 [get_ports "ja[4]"]
set_property IOSTANDARD LVCMOS12 [get_ports "ja[4]"]
set_property PACKAGE_PIN AF25 [get_ports "ja[5]"]
set_property IOSTANDARD LVCMOS12 [get_ports "ja[5]"]
set_property PACKAGE_PIN AE21 [get_ports "ja[6]"]
set_property IOSTANDARD LVCMOS12 [get_ports "ja[6]"]
set_property PACKAGE_PIN AM17 [get_ports "ja[7]"]
set_property IOSTANDARD LVCMOS12 [get_ports "ja[7]"]
