
.PHONY: all
all:
	python ../common/time.py artix7
	python ../common/time.py ku

clean:
	rm -rf .Xil
	rm -f *_webtalk.*
	rm -f tmp/*.log tmp/*.xdc tmp/*.tcl
	rm -f vivado*.jou vivado*.log
	rm -f vivado_*.str
